ekf_odom:
  ros__parameters:
    two_d_mode: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    frequency: 50.0
    publish_tf: true
    imu0: /imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_remove_gravitational_acceleration: true

ekf_map:
  ros__parameters:
    two_d_mode: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    frequency: 30.0
    publish_tf: true
    imu0: /imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    odom0: /odometry/gps
    odom0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

navsat_transform_node:
  ros__parameters:
    base_link_frame: base_link
    odom_frame: odom
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    two_d_mode: true
    use_odometry_yaw: false
    publish_tf: false
    transform_timeout: 0.2
